### ISSUE TITLE
crash on NVME disk

### ISSUE THREAD

**Issue by snltd** [snltd/illumos-telegraf-plugins#12]
```
panic: runtime error: index out of range [0] with length 0

goroutine 1510 [running]:
github.com/snltd/illumos-telegraf-plugins/inputs/disk_health.camelCase({0x0?, 0xc0007ec9c0?})
        /home/rob/go/src/github.com/snltd/illumos-telegraf-plugins/inputs/disk_health/disk_health.go:89 +0x99
github.com/snltd/illumos-telegraf-plugins/inputs/disk_health.parseNamedStats(0xc000076870, {0xc00009b800, 0xf, 0x1?})
        /home/rob/go/src/github.com/snltd/illumos-telegraf-plugins/inputs/disk_health/disk_health.go:51 +0x531
github.com/snltd/illumos-telegraf-plugins/inputs/disk_health.(*IllumosDiskHealth).Gather(0xc000076870, {0xc61c58, 0xc00002c200})
        /home/rob/go/src/github.com/snltd/illumos-telegraf-plugins/inputs/disk_health/disk_health.go:76 +0x1f2
github.com/influxdata/telegraf/models.(*RunningInput).Gather(0xc000076910, {0xc61c58, 0xc00002c200})
        /home/rob/go/src/github.com/influxdata/telegraf/models/running_input.go:117 +0x5a
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce.func1()
        /home/rob/go/src/github.com/influxdata/telegraf/agent/agent.go:484 +0x2e
created by github.com/influxdata/telegraf/agent.(*Agent).gatherOnce
        /home/rob/go/src/github.com/influxdata/telegraf/agent/agent.go:483 +0x12a
[ Mar 18 12:50:00 Stopping because all processes in service exited. ]
[ Mar 18 12:50:00 Executing stop method (:kill). ]
[ Mar 18 12:50:00 Executing start method ("/opt/site/lib/smf/method/telegraf.sh"). ]
[ Mar 18 12:50:00 Method "start" exited with status 0. ]
2023-03-18T12:50:00Z I! Starting Telegraf 1.16.3
panic: runtime error: index out of range [0] with length 0

goroutine 1530 [running]:
github.com/snltd/illumos-telegraf-plugins/inputs/disk_health.camelCase({0x0?, 0xc000d26f60?})
        /home/rob/go/src/github.com/snltd/illumos-telegraf-plugins/inputs/disk_health/disk_health.go:89 +0x99
github.com/snltd/illumos-telegraf-plugins/inputs/disk_health.parseNamedStats(0xc000148cd0, {0xc0019c4380, 0xf, 0x1?})
        /home/rob/go/src/github.com/snltd/illumos-telegraf-plugins/inputs/disk_health/disk_health.go:51 +0x531
github.com/snltd/illumos-telegraf-plugins/inputs/disk_health.(*IllumosDiskHealth).Gather(0xc000148cd0, {0xc61c58, 0xc0001ae260})
        /home/rob/go/src/github.com/snltd/illumos-telegraf-plugins/inputs/disk_health/disk_health.go:76 +0x1f2
github.com/influxdata/telegraf/models.(*RunningInput).Gather(0xc000148d70, {0xc61c58, 0xc0001ae260})
        /home/rob/go/src/github.com/influxdata/telegraf/models/running_input.go:117 +0x5a
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce.func1()
        /home/rob/go/src/github.com/influxdata/telegraf/agent/agent.go:484 +0x2e
created by github.com/influxdata/telegraf/agent.(*Agent).gatherOnce
        /home/rob/go/src/github.com/influxdata/telegraf/agent/agent.go:483 +0x12a
[ Mar 18 13:00:00 Stopping because all processes in service exited. ]
[ Mar 18 13:00:00 Executing stop method (:kill). ]
[ Mar 18 13:00:00 Executing start method ("/opt/site/lib/smf/method/telegraf.sh"). ]
[ Mar 18 13:00:00 Method "start" exited with status 0. ]
2023-03-18T13:00:00Z I! Starting Telegraf 1.16.3
panic: runtime error: index out of range [0] with length 0

goroutine 1516 [running]:
github.com/snltd/illumos-telegraf-plugins/inputs/disk_health.camelCase({0x0?, 0xc0014d6f30?})
        /home/rob/go/src/github.com/snltd/illumos-telegraf-plugins/inputs/disk_health/disk_health.go:89 +0x99
github.com/snltd/illumos-telegraf-plugins/inputs/disk_health.parseNamedStats(0xc000076c80, {0xc0019cb480, 0xf, 0x1?})
        /home/rob/go/src/github.com/snltd/illumos-telegraf-plugins/inputs/disk_health/disk_health.go:51 +0x531
github.com/snltd/illumos-telegraf-plugins/inputs/disk_health.(*IllumosDiskHealth).Gather(0xc000076c80, {0xc61c58, 0xc00002c980})
        /home/rob/go/src/github.com/snltd/illumos-telegraf-plugins/inputs/disk_health/disk_health.go:76 +0x1f2
github.com/influxdata/telegraf/models.(*RunningInput).Gather(0xc000076d20, {0xc61c58, 0xc00002c980})
        /home/rob/go/src/github.com/influxdata/telegraf/models/running_input.go:117 +0x5a
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce.func1()
        /home/rob/go/src/github.com/influxdata/telegraf/agent/agent.go:484 +0x2e
created by github.com/influxdata/telegraf/agent.(*Agent).gatherOnce
        /home/rob/go/src/github.com/influxdata/telegraf/agent/agent.go:483 +0x12a

```

**Comment by snltd** [comment]
fixt
